/**Problem45.java
TODO
@author Xiu Yi Tiger yixiu17@gmail.com
Created on2014-12-17
1:05:44 PM
 */
package Problem41to50;

/**
 * TODO Triangle, pentagonal, and hexagonal numbers are generated by the
 * following formulae:
 * 
 * Triangle Tn=n(n+1)/2 1, 3, 6, 10, 15, ... Pentagonal Pn=n(3n−1)/2 1, 5, 12,
 * 22, 35, ... Hexagonal Hn=n(2n−1) 1, 6, 15, 28, 45, ... It can be verified
 * that T285 = P165 = H143 = 40755.
 * 
 * Find the next triangle number that is also pentagonal and hexagonal.
 * 
 * Observation : every hexagonal number is a triangle number(more specifically,
 * ith hexagonal number is (i*2-1)th triangle number). So that we could save
 * some time to check pentagonal number.
 * 
 * Solution : loop through triangle numbers at odd index, find the first one
 * that is a hexagonal.
 * 
 * @author Tiger yi
 * 
 */
public class Problem45 {

	public void tph() {
		long n = 286;
		while (true) {
			if (n % 2 == 1) {
				long target = n * (n + 1) / 2;
				if (isPentagon(target)) {
					System.out.println(target);
					break;
				}
			}
			n += 1;
		}
	}

	public boolean isPentagon(long n) {
		long root = (long) (1 + Math.sqrt(1 + 24 * n)) / 6;
		if (root * (root * 3 - 1) / 2 == n) {
			System.out.println(root);
			return true;
		}
		return false;
	}

	public static void main(String[] args) {
		new Problem45().tph();

	}

}
