/**Problem29.java
TODO
@author Xiu Yi Tiger yixiu17@gmail.com
Created on2014-12-08
7:00:09 PM
 */
package Problem21to30;

import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

/**
 * TODO Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:
 * 
 * 22=4, 23=8, 24=16, 25=32 32=9, 33=27, 34=81, 35=243 42=16, 43=64, 44=256,
 * 45=1024 52=25, 53=125, 54=625, 55=3125 If they are then placed in numerical
 * order, with any repeats removed, we get the following sequence of 15 distinct
 * terms:
 * 
 * 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
 * 
 * How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100
 * and 2 ≤ b ≤ 100?
 * 
 * Solution : Loop through every numbers and compute every power of them.(use
 * BigInteger)
 * 
 * @author Tiger yi
 * 
 */
public class Problem29 {

	public void distinctPowers(int a, int b) {
		Set<BigInteger> s = new HashSet<BigInteger>();
		for (Integer ia = 2; ia < a + 1; ia++) {
			for (int ib = 2; ib < b + 1; ib++) {
				BigInteger bi = new BigInteger(ia.toString());
				if (!s.contains(bi.pow(ib))) {
					s.add(bi.pow(ib));
				}
			}
		}
		System.out.println(s.size());
	}

	public static void main(String[] args) {
		Problem29 P29 = new Problem29();
		P29.distinctPowers(100, 100);

	}

}
